#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS
#include "Battle/BattleTextResolver.h"
#include "Cards/CardData.h"
#include "Cards/CardInstance.h"
#include "Cards/Effects/DamageCardEffect.h"
#include "Cards/Effects/GainBlockCardEffect.h"
#include "Cards/Effects/DrawCardEffect.h"
#include "Cards/Effects/GainEnergyCardEffect.h"
#include "Cards/Effects/ApplyStatusCardEffect.h"
#include "Cards/Effects/SelectExhaustHandCardEffect.h"
#include "Combat/Combatant.h"
#include "Engine/World.h"
#include "Status/StatusData.h"

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAutomaticCardDescriptionTest,
	"SlayTheSpireDemo.Cards.AutomaticDescription.CompositionAndPreview",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FAutomaticCardDescriptionTest::RunTest(const FString& Parameters)
{
	UWorld* World = UWorld::CreateWorld(EWorldType::Game, false, NAME_None, nullptr, false);
	if (!TestNotNull(TEXT("World"), World)) return false;
	ACombatant* Source = World->SpawnActor<ACombatant>();
	if (!TestNotNull(TEXT("Source"), Source)) { World->DestroyWorld(false); return false; }
	Source->InitializeCombatant();
	UCardData* Definition = NewObject<UCardData>(World);
	Definition->Description = FText::FromString(TEXT("Stale authored text"));
	Definition->DefaultDestination = ECardDestination::Exhaust;
	UDamageCardEffect* First = NewObject<UDamageCardEffect>(Definition);
	UDamageCardEffect* Second = NewObject<UDamageCardEffect>(Definition);
	Second->BaseAmount = 3;
	Second->HitCount = 2;
	Second->UpgradedAmount = 7;
	Second->UpgradedHitCount = 3;
	UDrawCardEffect* Draw = NewObject<UDrawCardEffect>(Definition);
	Definition->Effects = {First, Draw, Second};
	UCardInstance* Card = NewObject<UCardInstance>(World);
	Card->Initialize(Definition, 1);
	TestTrue(TEXT("Automatic by default"), Definition->bAutoGenerateDescription);
	TArray<FText> Errors;
	TestTrue(TEXT("Duplicate effect argument names are local"), FBattleTextResolver::ValidateCardDefinition(Definition, Errors));
	TestEqual(TEXT("Array order, hit count, stale text ignored, exhaust appended"),
		FBattleTextResolver::ResolveCardDescription(Card, Source).ToString(),
		FString(TEXT("造成 6 点伤害。\n抽 1 张牌。\n造成 3 点伤害，共 2 次。\n消耗。")));
	TArray<FImmediatePreviewOperation> Operations;
	FImmediatePreviewOperation& Operation = Operations.AddDefaulted_GetRef();
	Operation.EffectIndex = 2;
	Operation.SemanticArgumentName = Second->DescriptionArgumentName;
	Operation.BaseAmount = 3;
	Operation.ResolvedAmount = 4;
	TestEqual(TEXT("Target override only affects its effect index"),
		FBattleTextResolver::ResolveCardRichDescriptionForImmediatePreview(Card, Source, Operations).ToString(),
		FString(TEXT("造成 6 点伤害。\n抽 1 张牌。\n造成 <PreviewIncrease>4</> 点伤害，共 2 次。\n<Exhaust>消耗。</>")));
	TestEqual(TEXT("Plain target preview stays markup free"),
		FBattleTextResolver::ResolveCardDescriptionForImmediatePreview(Card, Source, Operations).ToString(),
		FString(TEXT("造成 6 点伤害。\n抽 1 张牌。\n造成 4 点伤害，共 2 次。\n消耗。")));
	Definition->Effects.Swap(0, 1);
	Draw->DrawCount = 2;
	TestTrue(TEXT("Property edits and reorder are reflected without cached text"),
		FBattleTextResolver::ResolveCardDescription(Card, Source).ToString().StartsWith(TEXT("抽 2 张牌。\n造成 6 点伤害。")));
	UCardInstance* Upgraded = NewObject<UCardInstance>(World);
	Upgraded->Initialize(Definition, 2, true);
	TestTrue(TEXT("Upgraded amount and hit count"), FBattleTextResolver::ResolveCardDescription(Upgraded, Source).ToString().Contains(TEXT("造成 7 点伤害，共 3 次。")));
	Definition->Effects.Reset();
	TestEqual(TEXT("Exhaust-only card"), FBattleTextResolver::ResolveCardDescription(Card, Source).ToString(), FString(TEXT("消耗。")));
	TestEqual(TEXT("Exhaust keyword uses its own rich style"), FBattleTextResolver::ResolveCardRichDescription(Card, Source).ToString(), FString(TEXT("<Exhaust>消耗。</>")));
	Definition->DefaultDestination = ECardDestination::Discard;
	TestTrue(TEXT("Empty card"), FBattleTextResolver::ResolveCardDescription(Card, Source).IsEmpty());
	Definition->bAutoGenerateDescription = false;
	TestEqual(TEXT("Explicit custom compatibility"), FBattleTextResolver::ResolveCardDescription(Card, Source).ToString(), FString(TEXT("Stale authored text")));
	World->DestroyWorld(false);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAutomaticCardDescriptionEffectsTest,
	"SlayTheSpireDemo.Cards.AutomaticDescription.EffectVocabulary",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FAutomaticCardDescriptionEffectsTest::RunTest(const FString& Parameters)
{
	UWorld* World = UWorld::CreateWorld(EWorldType::Game, false, NAME_None, nullptr, false);
	if (!TestNotNull(TEXT("World"), World)) return false;
	ACombatant* Source = World->SpawnActor<ACombatant>();
	if (!TestNotNull(TEXT("Source"), Source)) { World->DestroyWorld(false); return false; }
	Source->InitializeCombatant();
	UCardData* Definition = NewObject<UCardData>(World);
	Definition->TargetType = ECardTargetType::Self;
	UGainBlockCardEffect* Block = NewObject<UGainBlockCardEffect>(Definition);
	UGainEnergyCardEffect* Energy = NewObject<UGainEnergyCardEffect>(Definition);
	UApplyStatusCardEffect* Status = NewObject<UApplyStatusCardEffect>(Definition);
	Status->StatusDefinition = NewObject<UStatusData>(Definition);
	Status->StatusDefinition->DisplayName = NSLOCTEXT("AutomaticCardDescriptionTests", "Strength", "力量");
	USelectExhaustHandCardEffect* Select = NewObject<USelectExhaustHandCardEffect>(Definition);
	Select->DescriptionArgumentName = NAME_None;
	Select->SelectionModeDescriptionArgumentName = NAME_None;
	Select->BaseSelectionMode = ESelectExhaustSelectionMode::Random;
	Select->UpgradedSelectionMode = ESelectExhaustSelectionMode::Player;
	Select->UpgradedSelectionCount = 2;
	Definition->Effects = {Block, Energy, Status, Select};
	UCardInstance* Card = NewObject<UCardInstance>(World);
	Card->Initialize(Definition, 1);
	TestEqual(TEXT("Chinese vocabulary and legacy None selection fields"),
		FBattleTextResolver::ResolveCardDescription(Card, Source).ToString(),
		FString(TEXT("获得 5 点格挡。\n获得 1 点能量。\n获得 1 层力量。\n随机消耗 1 张手牌。")));
	UCardInstance* Upgraded = NewObject<UCardInstance>(World);
	Upgraded->Initialize(Definition, 2, true);
	TestTrue(TEXT("Selection upgrade changes wording and count"), FBattleTextResolver::ResolveCardDescription(Upgraded, Source).ToString().EndsWith(TEXT("选择 2 张手牌消耗。")));
	Definition->TargetType = ECardTargetType::Enemy;
	Definition->Effects = {Status};
	TestEqual(TEXT("Enemy status wording"), FBattleTextResolver::ResolveCardDescription(Card, Source).ToString(), FString(TEXT("给予目标 1 层力量。")));
	World->DestroyWorld(false);
	return true;
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAutomaticCardDescriptionAssetsTest,
	"SlayTheSpireDemo.Cards.AutomaticDescription.ExistingAssets",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FAutomaticCardDescriptionAssetsTest::RunTest(const FString& Parameters)
{
	UWorld* World = UWorld::CreateWorld(EWorldType::Game, false, NAME_None, nullptr, false);
	if (!TestNotNull(TEXT("World"), World)) return false;
	ACombatant* Source = World->SpawnActor<ACombatant>();
	if (!TestNotNull(TEXT("Source"), Source)) { World->DestroyWorld(false); return false; }
	Source->InitializeCombatant();
	const TCHAR* Paths[] = {
		TEXT("Attacks/DA_Card_Strike"), TEXT("Attacks/DA_Card_PommelStrike"),
		TEXT("Attacks/DA_Card_TwinStrike"), TEXT("Attacks/DA_Card_Uppercut"),
		TEXT("Skills/DA_Card_Defend"), TEXT("Skills/DA_Card_SeeingRed"),
		TEXT("Skills/DA_Card_BurningPact"),
		TEXT("powers/DA_Card_Inflame")};
	for (const TCHAR* RelativePath : Paths)
	{
		const FString Path = FString(TEXT("/Game/SlayTheSpireDemo/Data/Cards/Ironclad/")) + RelativePath;
		UCardData* Definition = LoadObject<UCardData>(nullptr, *Path);
		if (!TestNotNull(*Path, Definition)) continue;
		TestTrue(TEXT("Existing asset adopts auto default without resave"), Definition->bAutoGenerateDescription);
		TArray<FText> Errors;
		TestTrue(*FString::Printf(TEXT("%s validates"), RelativePath), FBattleTextResolver::ValidateCardDefinition(Definition, Errors));
		for (const FText& Error : Errors) AddError(Error.ToString());
		for (bool bUpgraded : {false, true})
		{
			UCardInstance* Card = NewObject<UCardInstance>(World);
			Card->Initialize(Definition, 1, bUpgraded);
			const FString Description = FBattleTextResolver::ResolveCardDescription(Card, Source).ToString();
			TestFalse(TEXT("Existing card has generated text"), Description.IsEmpty());
			TestFalse(TEXT("No unresolved arguments"), Description.Contains(TEXT("{")) || Description.Contains(TEXT("?")));
			AddInfo(FString::Printf(TEXT("%s upgraded=%d: %s"), RelativePath, bUpgraded, *Description));
		}
	}
	World->DestroyWorld(false);
	return true;
}
#endif
